[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "alai"
version = "0.0.1"
dependencies = [
    "numpy"
]

[tool.setuptools.packages.find]
where = ["src"]